# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00a_constant.ipynb.

# %% auto 0
__all__ = ['ELECTRIC_CONSTANT', 'PI']

# %% ../nbs/00a_constant.ipynb 1
ELECTRIC_CONSTANT = 8.988e9 # N m^2/C^2

# %% ../nbs/00a_constant.ipynb 2
PI = 3.14 # pi number
