# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/21_electric_charge_and_electric_field.ipynb.

# %% auto 0
__all__ = ['Vector', 'Particle', 'Proton', 'Neutron', 'Electron', 'Force', 'CoulombLaw', 'ElectricField']

# %% ../nbs/21_electric_charge_and_electric_field.ipynb 3
from typing import Any
from dataclasses import dataclass, field

import vector

# %% ../nbs/21_electric_charge_and_electric_field.ipynb 8
class Vector:
    def __init__(self, x, y, z = None):
        self.x = x
        self.y = y
        self.z = z
    
    @property
    def magnitude(self):
        if self.x and self.y and self.z:
            return vector.obj(x=self.x, y=self.y, z=self.z).mag
        elif self.x and self.y:
            return vector.obj(x=self.x, y=self.y).rho
        else:
            raise ValueError("Hell no")

# %% ../nbs/21_electric_charge_and_electric_field.ipynb 20
@dataclass
class Particle:
    electric_charge: int
    coordinate: Vector
    
    def __post_init__(self):
        
        #self.electric_field = ElectricField()
        # if len(self.coordinate) == 3:
        #     self.coordinate = vector.obj(x=self.coordinate[0], y=self.coordinate[1], z=self.coordinate[2])
        # elif len(self.coordinate) == 2:
        #     self.coordinate = vector.obj(x=self.coordinate[0], y=self.coordinate[1])
        
        pass

# %% ../nbs/21_electric_charge_and_electric_field.ipynb 25
class Proton(Particle):
    pass

# %% ../nbs/21_electric_charge_and_electric_field.ipynb 26
class Neutron(Particle):
    pass

# %% ../nbs/21_electric_charge_and_electric_field.ipynb 27
class Electron(Particle):
    pass

# %% ../nbs/21_electric_charge_and_electric_field.ipynb 28
class Force:
    pass

# %% ../nbs/21_electric_charge_and_electric_field.ipynb 31
class CoulombLaw:
    
    def electric_force(self, q1, q2):
        pass

# %% ../nbs/21_electric_charge_and_electric_field.ipynb 34
class ElectricField(Particle):
    
    def magnitude(self, measure_coodrinate): # the coordinate of where the field is measured
        
        """"
        Calculate the magnitude of a point charge to where the field is measured
        """
        
        distance = self.coordinate.subtract(measure_coodrinate)
        distance_squared = distance.rho2
        unit_vector = distance.unit()
        
        print(f"electric_field = {self.electric_charge}")
        
        return ELECTRIC_CONSTANT * (self.electric_charge / distance_squared) * unit_vector
