# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/23_electric_potential.ipynb.

# %% auto 0
__all__ = ['ElectricPotential']

# %% ../nbs/23_electric_potential.ipynb 3
class ElectricPotential:
    pass
